apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: {{ .Values.deployment.scaling.minReplicas }}
  maxReplicas: {{ .Values.deployment.scaling.maxReplicas }}
  targetCPUUtilizationPercentage: 80