apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace:  {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    # The below annotation will generate certs injected to the cluster-tls secret for use in pods
    service.alpha.openshift.io/serving-cert-secret-name: cluster-tls
spec:
  ports:
    {{- range $key, $val := .Values.deployment.ports }}
    - name: {{ $key }}
      port: {{ $val.containerPort }}
      targetPort: {{ $val.containerPort }}
      protocol: {{ $val.protocol | quote }}
    {{- end }}
  selector:
    app: {{ .Chart.Name }}